version: "3.4"

services:
  db-processor:
    container_name: db-processor
    image: postgres:12
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
#    command: ["postgres", "-c", "log_statement=all"]