name: e2e test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    
    - name: Install Node.js wait-port
      run: yarn global add wait-port
      
    - name: Launch local sandbox
      run: docker run -d -p 9988:9988 -p 9944:9944 public.ecr.aws/e4o7i5u6/polkadot-basilisk-testnet:0.1.25
      
    - name: Wait for Basilisk Node port :9988
      shell: bash
      timeout-minutes: 5
      run: wait-port 9988
    
    - name: Wait 50 seconds for sandbox
      uses: jakejarvis/wait-action@master
      with:
        time: '50s'
    
    - run: yarn run migrate:lbp
    - run: yarn run migrate:xyk
    - run: yarn run test:unit
    - run: yarn run test:e2e
